package prv.saevel.drools.workshop.users;

import prv.saevel.drools.workshop.users.User;
import prv.saevel.drools.workshop.users.Account;
import prv.saevel.drools.workshop.users.Currency;
import java.util.LinkedList;

global prv.saevel.drools.workshop.users.UsersService usersService;

rule "Add default account"
    when
        $newUser : User($userId : id, $anyCountry : country, accounts == null)
    then
        Account $defaultAccount = new Account($userId, 0.0, Currency.USD);
        LinkedList<Account> $accounts = new LinkedList<Account>();
        $accounts.add($defaultAccount);
        $newUser.setAccounts($accounts);
        usersService.save($newUser);
    end